In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset=pd.read_csv("Example.csv")
dataset

,Index,count,hate_speech,offensive_language,neither,class,tweet
0,0,3,0,0,3,2,!!! RT @mayasolovely: As a woman you shouldn't...
1,1,3,0,3,0,1,!!!!! RT @mleew17: boy dats cold...tyga dwn ba...
2,2,3,0,3,0,1,!!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...
3,3,3,0,2,1,1,!!!!!!!!! RT @C_G_Anderson: @viva_based she lo...
4,4,6,0,6,0,1,!!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...
...,...,...,...,...,...,...,...
24778,25291,3,0,2,1,1,you's a muthaf***in lie &#8220;@LifeAsKing: @2...
24779,25292,3,0,1,2,2,"you've gone and broke the wrong heart baby, an..."
24780,25294,3,0,3,0,1,young buck wanna eat!!.. dat nigguh like I ain...
24781,25295,6,0,6,0,1,youu got wild bitches tellin you lies
24782,25296,3,0,0,3,2,~~Ruffled | Ntac Eileen Dahlia - Beautiful col...

In [3]:
dataset.isnull().sum()

Index                 0
count                 0
hate_speech           0
offensive_language    0
neither               0
class                 0
tweet                 0
dtype: int64

In [4]:
dataset.describe()

,Index,count,hate_speech,offensive_language,neither,class
count,24783.000000,24783.000000,24783.000000,24783.000000,24783.000000,24783.000000
mean,12681.192027,3.243473,0.280515,2.413711,0.549247,1.110277
std,7299.553863,0.883060,0.631851,1.399459,1.113299,0.462089
min,0.000000,3.000000,0.000000,0.000000,0.000000,0.000000
25%,6372.500000,3.000000,0.000000,2.000000,0.000000,1.000000
50%,12703.000000,3.000000,0.000000,3.000000,0.000000,1.000000
75%,18995.500000,3.000000,0.000000,3.000000,0.000000,1.000000
max,25296.000000,9.000000,7.000000,9.000000,9.000000,2.000000

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24783 entries, 0 to 24782
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Index               24783 non-null  int64
 1   count               24783 non-null  int64
 2   hate_speech         24783 non-null  int64
 3   offensive_language  24783 non-null  int64
 4   neither             24783 non-null  int64
 5   class               24783 non-null  int64
 6   tweet               24783 non-null  object
dtypes: int64(6), object(1)
memory usage: 1.3+ MB

In [6]:
dataset['labels']=dataset['class'].map({0:"Hate Speech",
                                        1: "Offensive Language",
                                        2: "No hate or offensive language"})

In [7]:
dataset

,Index,count,hate_speech,offensive_language,neither,class,tweet,labels
0,0,3,0,0,3,2,!!! RT @mayasolovely: As a woman you shouldn't...,No hate or offensive language
1,1,3,0,3,0,1,!!!!! RT @mleew17: boy dats cold...tyga dwn ba...,Offensive Language
2,2,3,0,3,0,1,!!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...,Offensive Language
3,3,3,0,2,1,1,!!!!!!!!! RT @C_G_Anderson: @viva_based she lo...,Offensive Language
4,4,6,0,6,0,1,!!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...,Offensive Language
...,...,...,...,...,...,...,...,...
24778,25291,3,0,2,1,1,you's a muthaf***in lie &#8220;@LifeAsKing: @2...,Offensive Language
24779,25292,3,0,1,2,2,"you've gone and broke the wrong heart baby, an...",No hate or offensive language
24780,25294,3,0,3,0,1,young buck wanna eat!!.. dat nigguh like I ain...,Offensive Language
24781,25295,6,0,6,0,1,youu got wild bitches tellin you lies,Offensive Language
24782,25296,3,0,0,3,2,~~Ruffled | Ntac Eileen Dahlia - Beautiful col...,No hate or offensive language

In [8]:
data = dataset[["tweet","labels"]]

In [9]:
data

,tweet,labels
0,!!! RT @mayasolovely: As a woman you shouldn't...,No hate or offensive language
1,!!!!! RT @mleew17: boy dats cold...tyga dwn ba...,Offensive Language
2,!!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...,Offensive Language
3,!!!!!!!!! RT @C_G_Anderson: @viva_based she lo...,Offensive Language
4,!!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...,Offensive Language
...,...,...
24778,you's a muthaf***in lie &#8220;@LifeAsKing: @2...,Offensive Language
24779,"you've gone and broke the wrong heart baby, an...",No hate or offensive language
24780,young buck wanna eat!!.. dat nigguh like I ain...,Offensive Language
24781,youu got wild bitches tellin you lies,Offensive Language
24782,~~Ruffled | Ntac Eileen Dahlia - Beautiful col...,No hate or offensive language

In [10]:
import re
import nltk
import string

In [11]:
from nltk.corpus import stopwords
stopwords=set(stopwords.words("english"))

In [12]:
stemmer=nltk.SnowballStemmer("english")

In [13]:
def clean_data(text):
    text = str(text).lower()
    text=re.sub('https?://\S+|www\.S+','',text)
    text=re.sub('\[.*?\]','',text)
    text=re.sub('<.*?>+','',text)
    text=re.sub('[%s]'%re.escape(string.punctuation),'',text)
    text=re.sub('\n','',text)
    text=re.sub('\w*\d\w*','',text)
    #stope words removal
    text=[word for word in text.split()if word not in stopwords]
    text="".join(text)
    text=[stemmer.stem(word) for word in text]
    text="".join(text)
    return text

In [14]:
data["tweet"]=data["tweet"].apply(clean_data)

C:\Users\supri\AppData\Local\Temp\ipykernel_4696\2823468588.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["tweet"]=data["tweet"].apply(clean_data)

In [15]:
data

,tweet,labels
0,rtmayasolovelywomanshouldntcomplaincleaninghou...,No hate or offensive language
1,rtboydatscoldtygadwnbadcuffindathoeplace,Offensive Language
2,rturkindofbranddawgrteverfuckbitchstartcryconf...,Offensive Language
3,rtcgandersonvivabasedlookliketranny,Offensive Language
4,rtshenikarobertsshithearmighttruemightfakerbit...,Offensive Language
...,...,...
24778,yousmuthafinliecoreyemanuelrighttltrashminebib...,Offensive Language
24779,youvegonebrokewrongheartbabydroveredneckcrazy,No hate or offensive language
24780,youngbuckwannaeatdatnigguhlikeaintfuckindis,Offensive Language
24781,youugotwildbitchestellinlies,Offensive Language
24782,ruffledntaceileendahliabeautifulcolorcombinati...,No hate or offensive language

In [16]:
x=np.array(data["tweet"])
y=np.array(data["labels"])

In [17]:
x

array(['rtmayasolovelywomanshouldntcomplaincleaninghouseampmanalwaystaketrash',
       'rtboydatscoldtygadwnbadcuffindathoeplace',
       'rturkindofbranddawgrteverfuckbitchstartcryconfusedshit', ...,
       'youngbuckwannaeatdatnigguhlikeaintfuckindis',
       'youugotwildbitchestellinlies',
       'ruffledntaceileendahliabeautifulcolorcombinationpinkorangeyellowampwhitecoll'],
      dtype=object)

In [18]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split

In [19]:
countVector=CountVectorizer()
x=countVector.fit_transform(x)

In [20]:
x

<24783x24502 sparse matrix of type '<class 'numpy.int64'>'
	with 24778 stored elements in Compressed Sparse Row format>

In [21]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=42)
x_train

<16604x24502 sparse matrix of type '<class 'numpy.int64'>'
	with 16601 stored elements in Compressed Sparse Row format>

In [22]:
from sklearn.tree import DecisionTreeClassifier

In [23]:
df=DecisionTreeClassifier()
df

DecisionTreeClassifier()

In [ ]:
df.fit(x_train,y_train)
y_pred=df.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
sns.heatmap(cm,annot=True,fmt=".1f",cmap='OrRd')

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

In [ ]:
sample=  " Keeks is a bitch she curves everyone lol I walked into a conversation like this. Smh"

sample=clean_data(sample)

In [ ]:
sample

In [ ]:
dataa=countVector.transform([sample]).toarray()
dataa

In [ ]:
df.predict(dataa)